# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

- name: Update timezone (debian)
  become: true
  ansible.builtin.command:
    cmd: "timedatectl set-timezone '{{ clock_timezone }}'"
  when:
    - ansible_os_family|lower == 'debian'
